packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # Dev tooling
  eslint: ^9.28.0
  prettier: ^3.5.3
  postcss: ^8.5.6
  tailwindcss: ^3.4.15
  typescript: ^5.8.3

  # Misc
  class-variance-authority: "^0.7.1"
  tailwind-merge: "^3.3.1"
  tsup: "^8.4.0"
  zod: ^3.24.3

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.1.6
    "@types/react-dom": ^19.1.5

onlyBuiltDependencies:
  - esbuild
